title: "Aneesh Kodali"
email: aneesh.kodali@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Aspiring software engineer with experience in working with data and translating problems into logic. As a data analyst, I spent most of my time preparing data for further analysis and consumption by stakeholders. Transitioning into software engineering allows me to continue applying my quantitative background towards creating processes that can improve and automate the data ingestion-to-insight journey for an organization. I hope to continue taking inputs and building out capabilities that can better a company’s product/service or insight into its operations.
baseurl: "/" 
url: "/portfolio-mlh" 
github_username:  aneeshkodali

sass:
  sass_dir: _sass

icon: ./assets/img/profile_pic.jpeg